language: node_js
node_js: node
python: '3.6'
dist: xenial

before_script:
 - npm install -g gulp-cli

script:
 - npm test -s

after_success:
 - bash <(curl -s https://codecov.io/bash) -f coverage/unit/coverage-final.json -F unit
 - bash <(curl -s https://codecov.io/bash) -f coverage/integration/coverage-final.json -F integration
 - npm run doc
 - bash <(curl -s https://jgleitz.github.io/travis-deploy-gh-pages/deploy.sh) doc/*
