language: node_js
node_js: node

before_script:
 - npm install -g gulp

script:
 - gulp lint
 - gulp test

after_success:
 - bash <(curl -s https://codecov.io/bash) -f build/coverage.lcov
 - gulp doc
 - bash <(curl -s https://jgleitz.github.io/travis-deploy-gh-pages/deploy.sh) build/doc/*

